server:
  port: 8181
 
spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  thymeleaf:
    cache: false

  #配置数据源
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      #charaterEncoding设置编码格式
      #serverTimezone设置时区
      url: jdbc:mysql://47.99.183.187:3306/shop?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root

mybatis:
    #mybatis扫描配置
    mapper-locations: classpath:mapper/*.xml
    #开启sql日志
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

images:
  path: D:\images\