server:
  port: 8080
 
spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

  #配置数据源
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      #charaterEncoding设置编码格式
      #serverTimezone设置时区
      url: jdbc:mysql://localhost:3306/shop?useUnicode=true&charaterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456

mybatis:
#mybatis扫描配置
    mapper-locations: classpath:mapper/*.xml